### ISSUE TITLE
Uberspace hosting does not allow Connection: Keep-Alive

### ISSUE THREAD

**Issue by technopagan** [findingmarbles/Retromat#61]
HTTP connection keep-alive is a common web performance improvement because it enables assets to re-use an existing connection instead of having to go through the whole TCP+HTTP handshakes routine again. See https://www.webpagetest.org/performance_optimization.php?test=180307_YN_e2310cee72ead4fa3318d29584ed6b97&run=5#keep_alive_enabled to identify that Retromat is currently not using Connection: keep-alive.

Sadly, we currently cannot simply active Connection: keep-alive on Uberspace because it has been disabled by the Uberspace admins: 
<img width="382" alt="screen shot 2018-03-07 at 9 14 19 pm" src="https://user-images.githubusercontent.com/61264/37115946-fb8ac72c-224c-11e8-9dfa-bb960da27f67.png">

Forcibly re-enabling it via .htaccess is not possible. We can only set the HTTP header that suggests keep-alive to the client:
```
<ifModule mod_headers.c>
    Header set Connection keep-alive
</ifModule>
```
But as long as the server doesn't truly allow keep-alive, clients would try to re-use a connection only to find that it has been closed by the server.

Proposed fix to this issue: contact Uberspace and inquire about Connection: keep-alive and if it can be enabled or would be enabled on their new Uberspace 7 machines.

**Comment by fiddike** [comment]
Thank you for pointing that out! Just sent a request to the uberspace team. I CCed the email address I found on your website. Curious what we'll find out :-)

**Comment by technopagan** [comment]
@fiddike 🎉🙏👍 Thank you for following up on this! Uberspace has now activated Keep-Alive and the results are already visible: https://www.webpagetest.org/result/180319_C0_98478066ae4c8bbffa56070ba851c44b/7/details/#waterfall_view_step1 Nice!
