### ISSUE TITLE
Feature Request: Allow to filter for remote teams

### ISSUE THREAD

**Issue by xi** [findingmarbles/Retromat#66]
Many activities are not easy to do for remote teams. It would be nice if it was possible to have a filter that only shows activities that are relevant for them.

**Comment by findingmarbles** [comment]
I thought about doing that once and then found that I could adapt the overwhelming majority of activities to work for remote teams. I think, the physical ones like Constellation and Take a Stand were the only exceptions. But it's been a while. Do you have examples for activities that can't be adapted for remote teams?

**Comment by xi** [comment]
Thanks for the feedback. I also noticed that many activities can be adapted (after writing this request).

I think whether an activity can be adapted also depends on the tools you have available. And while many can be adapted, it is easier for some and harder for others.

I am not sure if these fuzzy concepts can be baked into a useful feature. I will come back if I have a more practical idea.
